apiVersion: v1
kind: Service
metadata:
  name: addressbook-service
  labels:
    app: addressbook-project
spec:
  selector:
    app: addressbook-project
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30180
